version: '3.8'

services:
  mongodb-example:
    container_name: mongodb-example
    image: mongo:latest
    ports:
    - target: 27017
      published: 27017
      protocol: tcp
      mode: host
    environment:
      MONGO_INITDB_ROOT_USERNAME: yasin
      MONGO_INITDB_ROOT_PASSWORD: yasin
      MONGO_INITDB_DATABASE: admin

    volumes:
      - "mongo-data1:/data/db"

  mongodb-example2:
    container_name: mongodb-example2
    image: mongo:latest
    ports:
    - target: 27017
      published: 27018
      protocol: tcp
      mode: host
    environment:
      MONGO_INITDB_ROOT_USERNAME: yasin
      MONGO_INITDB_ROOT_PASSWORD: yasin
      MONGO_INITDB_DATABASE: admin

    #longsintax
    volumes:
    - type: volume
      source: mongo-data2
      target: /data/db
      read_only: false
      
volumes:
  mongo-data1:
    name: mongo-data1
  mongo-data2:
    name: mongo-data2